### ISSUE TITLE
Is this what you wanted in this document? 

### ISSUE THREAD

**Issue by cheyennelmoore** [Bucknell-Biol364/Petrascheck-et-al.-2007#1]
https://github.com/Bucknell-Biol364/Petrascheck-et-al.-2007/blob/5f037e7ad781b92d65905bf06b2ad2b8cadf544c/Replication.Rmd#L2
@KField-Bucknell  
If you have time could you take a quick look and let me know if this is this what you had in mind here? Or do you want more explicit detail on attempts to replicate?

Thanks!
cc: @ianvogel

**Comment by KField-Bucknell** [comment]
Yes, that looks very good.
